### ISSUE TITLE
Panda and Pathlib Issue

### ISSUE THREAD

**Issue by Blackfoxx88** [guimatheus92/Bot_SpaceCrypto#1]
having this error, it wont install directly, been trying to get around it for about 5 hours now. stil not working

**### Pandas Error:**
```
 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
```

### **Pathlib Error:**
```
Collecting pathlib==1.0.1
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

```
× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by guimatheus92** [comment]
That's quite a strange error, which version of `python` did you install? You can check running the following code: `python --version`

**Comment by dicroh** [comment]
Mesmo erro aqui.
Python 3.10.2

Resultado do freeze:

appdirs==1.4.4
APScheduler==3.6.3
asgiref==3.5.0
autopep8==1.6.0
cachetools==4.2.2
certifi==2021.10.8
charset-normalizer==2.0.10
colorama==0.4.4
deepdiff==5.7.0
Django==4.0.1
idna==3.3
image==1.5.33
MouseInfo==0.1.3
mss==6.1.0
numpy==1.21.4
opencv-python==4.5.4.60
ordered-set==4.0.2
packaging==21.3
Pillow==9.0.0
PyAutoGUI==0.9.53
pyclick==0.0.2
pycodestyle==2.8.0
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pynput==1.7.6
pyparsing==3.0.6
pyperclip==1.8.2
PyRect==0.1.4
PyScreeze==0.1.28
pytesseract==0.3.8
python-telegram-bot==13.8.1
python3-xlib==0.15
pytweening==1.0.4
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
requests==2.26.0
six==1.16.0
sqlparse==0.4.2
telegram-send==0.25
tesseract==0.1.3
toml==0.10.2
tornado==6.1
tzdata==2021.5
tzlocal==4.1
urllib3==1.26.8
xlib==0.21

**Comment by guimatheus92** [comment]
@dicroh mas o seu Python você instalou a versão `Python 3.10.2` pelo que você me mandou, o certo é a versão `3.9.9` que eu recomendei. Desinstala e instala de novo, na duvida segue o tutorial que eu deixei pronto aqui já https://github.com/guimatheus92/Bot_SpaceCrypto/wiki/How-to-execute-SpaceCrypto-bot. Não esquece de ler tudo certinho e não pular nenhuma etapa das minhas recomendações, porque cada computador tem sua peculiaridade, aí evita erro.

**Comment by dicroh** [comment]
> @dicroh mas o seu Python você instalou a versão `Python 3.10.2` pelo que você me mandou, o certo é a versão `3.9.9` que eu recomendei. Desinstala e instala de novo, na duvida segue o tutorial que eu deixei pronto aqui já https://github.com/guimatheus92/Bot_SpaceCrypto/wiki/How-to-execute-SpaceCrypto-bot. Não esquece de ler tudo certinho e não pular nenhuma etapa das minhas recomendações, porque cada computador tem sua peculiaridade, aí evita erro.

Ok, vou remover e testar novamente

**Comment by Blackfoxx88** [comment]
> python --

Thank you for the reply. 

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>


Pip Freeze:
MouseInfo==0.1.3
mss==6.1.0
numpy==1.21.4
opencv-python==4.5.4.60
pathlib2==2.3.7.post1
PyAutoGUI==0.9.53
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pyperclip==1.8.2
PyRect==0.1.4
PyScreeze==0.1.28
pytweening==1.0.4
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
six==1.16.0
tzdata==2021.5
tzlocal==4.1

**Comment by guimatheus92** [comment]
@Blackfoxx88 you have the same issue as @dicroh, so make sure to take a look at the [README.md](https://github.com/guimatheus92/Bot_BombCrypto/blob/main/README.md) file, you will see that you will need to install `Python 3.9.9` version. So uninstall your current python version and install the correct one. You can also follow the tutorial available on how to install [Python](https://github.com/guimatheus92/Bot_BombCrypto/wiki/How-to-execute-BombCrypto-bot).

**Comment by Blackfoxx88** [comment]
> 

Copy that. Will update after installing 3.9.9. Thank you.

**Comment by Blackfoxx88** [comment]
> @Blackfoxx88 you have the same issue as @dicroh, so make sure to take a look at the [README.md](https://github.com/guimatheus92/Bot_BombCrypto/blob/main/README.md) file, you will see that you will need to install `Python 3.9.9` version. So uninstall your current python version and install the correct one. You can also follow the tutorial available on how to install [Python](https://github.com/guimatheus92/Bot_BombCrypto/wiki/How-to-execute-BombCrypto-bot).

It's working now. Thank you so much! 
![image](https://user-images.githubusercontent.com/99056652/154498973-f8b33238-4e1c-495f-bb0e-7274aba1372e.png)

**Comment by Blackfoxx88** [comment]
Last Question, what do you mean profile for multi accounts? Profile from the Brave Browser? Beacause even i try to put names, still it says 0 profiles. Thank you.

**Comment by guimatheus92** [comment]
@Blackfoxx88 Yes, it's the exactly same name as Brave profile without any blank or spaces. But you will only use this feature if you changed the parameter `enable_multiaccount: False` to `enable_multiaccount: True`. If you keep as `False`, it won't use the profile, so this message should not be seen.

**Comment by Blackfoxx88** [comment]
> @Blackfoxx88 Yes, it's the exactly same name as Brave profile without any blank or spaces. But you will only use this feature if you changed the parameter `enable_multiaccount: False` to `enable_multiaccount: True`. If you keep as `False`, it won't use the profile, so this message should not be seen.

Thank you for that. Already did those still gives me 0 profiles. already did the flags also.

![image](https://user-images.githubusercontent.com/99056652/154502148-b890fd13-ae0d-4cc5-a649-09f930723dcc.png)
![image](https://user-images.githubusercontent.com/99056652/154502181-8befa369-3e87-447e-bca1-491ce77a9b8a.png)

**Comment by Blackfoxx88** [comment]
> > > @Blackfoxx88 Yes, it's the exactly same name as Brave profile without any blank or spaces. But you will only use this feature if you changed the parameter `enable_multiaccount: False` to `enable_multiaccount: True`. If you keep as `False`, it won't use the profile, so this message should not be seen.
> > 
> > 
> > Thank you for that. Already did those still gives me 0 profiles. already did the flags also.
> > ![image](https://user-images.githubusercontent.com/99056652/154502148-b890fd13-ae0d-4cc5-a649-09f930723dcc.png) ![image](https://user-images.githubusercontent.com/99056652/154502181-8befa369-3e87-447e-bca1-491ce77a9b8a.png)
> 
> That's super strange! Change the parameter `enable_multiaccount` to `False` please, run the bot and go straight to the game and leave the mouse, check after a few seconds if the bot will run, if not send me the print. Also, make sure that your screen is `100%` in the scale of your computer.
> 
> In case it does not work, I will send you a script so I can get the results from your profile.

Done running with Multiaccount turned off. 100% scale also in maximized window. mouse moves 1 time. then stops at Glab Studios logo. doesent click Connect wallet also. 

Tried manually logging it in, and run "ïn-game" it only clicks sapceship 1 time then stops at the center.

**Comment by Blackfoxx88** [comment]
> Nice, so bot **it's working**! The problem now, is that it's not matching the same images I shared from the one you have on your screen. So you'll need to change those as I said in the third topic of `Observations` from [here](https://github.com/guimatheus92/Bot_SpaceCrypto#observations). So you'll need to replace the same images with same names in the path `/static/img/game`.

Got it. will Screencap images  now. Will update once done. Thank you @guimatheus92

**Comment by Blackfoxx88** [comment]
Done replacing the images. It's working fine now. Problem is i can't use Multiaccounts, since it still says 0 profile.

**Comment by Blackfoxx88** [comment]
> > Hi @guimatheus92 , Thank you. Done replacing the images. It's working fine now. Problem is i can't use Multiaccounts, since it still says 0 profile.
> 
> @Blackfoxx88 Great news! But do you want to use multiaccounts or that way is already good for you?

@guimatheus92 yes, i want to use multi account. ☺
