### ISSUE TITLE
Sugestão de redimensionamento e múltiplas janelas.

### ISSUE THREAD

**Issue by legnatv** [guimatheus92/Bot_SpaceCrypto#11]
Seria interessante poder trabalhar com o bot em janelas pequenas, 50% a 67% por exemplo, e redimensionamento automático para o tamanho que você programou, evitando assim falhas para reconhecer os pixels, isso ajudaria ter várias janelas trabalhando ao mesmo tempo e sobre nossa visão.

**Comment by legnatv** [comment]
Ta de parabéns com o bot, estou gostando, pretende adicionar surrender nos niveis 5/10/15?

**Comment by guimatheus92** [comment]
> Ta de parabéns com o bot, estou gostando, pretende adicionar surrender nos niveis 5/10/15?

Obrigadão, que bom que está dando certo! Foi uma sugestão do @evertonurbanii também no tópico [Selecionar até BOSS XX (SURRENDER)](https://github.com/guimatheus92/Bot_SpaceCrypto/issues/9), provavelmente vou adicionar sim! Mas ainda tem algumas coisas pra eu priorizar antes.

**Comment by legnatv** [comment]
> > Ta de parabéns com o bot, estou gostando, pretende adicionar surrender nos niveis 5/10/15?
> 
> Obrigadão, que bom que está dando certo! Foi uma sugestão do @evertonurbanii também no tópico [Selecionar até BOSS XX (SURRENDER)](https://github.com/guimatheus92/Bot_SpaceCrypto/issues/9), provavelmente vou adicionar sim! Mas ainda tem algumas coisas pra eu priorizar antes.

Top, estarei sempre aqui acompanhando o seu trabalho.
