### ISSUE TITLE
Poderia me ajudar com esse erro? 

### ISSUE THREAD

**Issue by evertonurbanii** [guimatheus92/Bot_SpaceCrypto#12]
![AnyDesk_1FmwP4Nyqg](https://user-images.githubusercontent.com/40852711/154736497-d15e952e-0a83-4de7-91d9-a3376cdb0c40.png)

Poderia me ajudar com esse erro? 
https://i.imgur.com/6YhB4OH.png

**Comment by felipepu** [comment]
same issue here

**Comment by guimatheus92** [comment]
Qual a versão do Python que você instalou? Você pode conferir digitando o comando: `python --version`. Se a versão instalada na sua máquina for diferente da versão `3.9.9` que eu recomendei. Desinstala e instala de novo, na duvida segue o tutorial que eu deixei pronto aqui já [How-to-execute-SpaceCrypto-bot](https://github.com/guimatheus92/Bot_SpaceCrypto/wiki/How-to-execute-SpaceCrypto-bot). Não esquece de ler tudo certinho e não pular nenhuma etapa das minhas recomendações, porque cada computador tem sua peculiaridade, aí evita erro.
Se a sua versão for diferente da `3.9.9`, me avise pra eu fechar essa issue.

**Comment by evertonurbanii** [comment]
fiz uma nova instalação, reiniciei a maquina, todos os processos normais.. td com a versão 3.9.9

**Comment by evertonurbanii** [comment]
Perdão... vi agora e ele atualizou.. ta na versão 3.10.. vou refazer td e aviso se deu certo

**Comment by evertonurbanii** [comment]
Qual comando para desinstalar via cmd o python, mesmo desinstalando... ele ainda acusa a versão 3.10 quando aplica o comendo python --version

**Comment by guimatheus92** [comment]
> Qual comando para desinstalar via cmd o python, mesmo desinstalando... ele ainda acusa a versão 3.10 quando aplica o comendo python --version

Desinstala como se fosse um programa qualquer, não precisa ser via `cmd`. Esse é um tipo de pergunta que tem no google/youtube facilmente, assim facilita sua vida.

**Comment by evertonurbanii** [comment]
eu fiz isso.. ele desintalou a versão 3.9 q vc recomendou.. e continuava aparecendo a versão 3.10 instalada... achei o comando aqui.. to aplicando: Get-Package "*python*" | Uninstall-Package

**Comment by guimatheus92** [comment]
@evertonurbanii deu certo seu bot então? Posso fechar essa issue?
