### ISSUE TITLE
Error when enabling multi-account

### ISSUE THREAD

**Issue by Romankriptoman** [guimatheus92/Bot_SpaceCrypto#14]
![image](https://user-images.githubusercontent.com/99992360/154748010-082a43a7-400f-4da2-95d9-c7866441cb64.png)
If the value is False, everything works without errors, as soon as I turn on True and start the bot, it throws an error.
![image](https://user-images.githubusercontent.com/99992360/154748220-441c5d82-80d7-4031-ae7d-54971169f86c.png)
Deleted everything and made a new one, the same error, help me figure it out!

**Comment by guimatheus92** [comment]
> ![image](https://user-images.githubusercontent.com/99992360/154748010-082a43a7-400f-4da2-95d9-c7866441cb64.png) If the value is False, everything works without errors, as soon as I turn on True and start the bot, it throws an error. ![image](https://user-images.githubusercontent.com/99992360/154748220-441c5d82-80d7-4031-ae7d-54971169f86c.png) Deleted everything and made a new one, the same error, help me figure it out!

As the `config.yaml` file says: `If you enable multiaccount, don't forget to set the profile names below`, so you need to set the exactly same name from your Brave profile (keep the name without blanks) in the parameter `multiaccount_names`.

If you still getting error after that, can you please create a new file called multi.py and paste the following code in it and run?

```
import pandas as pd
from pywinauto import Desktop

# Get all windows opens
windows = Desktop(backend="uia").windows()
window = [w.window_text() for w in windows]

# Create dataframe
df_windows = pd.DataFrame(window, columns =['WebBrowser'])

# Export to csv
df_windows.to_csv('window.csv', index=False)
```
After you run this code, it will create a file called `window.csv`, send this file in here so I can check the result please.

**Comment by Romankriptoman** [comment]
I tried as you wrote, the result is the same error
[window.csv](https://github.com/guimatheus92/Bot_SpaceCrypto/files/8100063/window.csv)
.

**Comment by guimatheus92** [comment]
> I tried as you wrote, the result is the same error [window.csv](https://github.com/guimatheus92/Bot_SpaceCrypto/files/8100063/window.csv) .

Does your profile is called `Profil1` and `Profil2`?
It's quite strange the output you got, what language are you using in `Brave` and also in `SO`? Because there's a lot of different characters than english, so I'd suggest to use english instead.

If I run the same query as I asked you, look at my output below, it's completely different than yours:

```
'NVIDIA GeForce Overlay DT',
 'Alternador de Tarefas',
 '● spg.ipynb - Documentos - Visual Studio Code',
 'East US vDesktop',
 'Multiaccounts not working? · Issue #8 · guimatheus92/Bot_SpaceCrypto e mais 7 páginas - Pessoal — Microsoft\u200b Edge',

 'Discord',
 'NVIDIA GeForce Overlay',
 'Área de Trabalho Remota',

 'Barra de Tarefas',
'Bombcrypto - Brave: BCOIN_2',
'Bombcrypto - Brave: BCOIN_1',
'Space Crypto - Brave: SPG_1',

 'Program Manager'
```

**Comment by Romankriptoman** [comment]
I changed the language in Windows and everything worked, thanks.
![image](https://user-images.githubusercontent.com/99992360/154774660-c8bf975b-bdd8-4393-a365-acda4ed15980.png)
