### ISSUE TITLE
Bot nao da OK nessa tela.

### ISSUE THREAD

**Issue by rogeriojim** [guimatheus92/Bot_SpaceCrypto#18]
![bug](https://user-images.githubusercontent.com/7713455/154768695-b84583c8-f66f-460b-a9eb-d0f764557c6a.png)

O Bot precisa dar OK nessa tela. Fica parado o tempo do reload da pagina.

**Comment by mittwz** [comment]
Se não funcionou o click nesta tela, você precisa substituir a imagem desse CLOSE lá nos arquivos \static\img\game

**Comment by guimatheus92** [comment]
> ![bug](https://user-images.githubusercontent.com/7713455/154768695-b84583c8-f66f-460b-a9eb-d0f764557c6a.png)
> 
> O Bot precisa dar OK nessa tela. Fica parado o tempo do reload da pagina.

O bot não está saindo da tela de erro do jogo, é isso?
Caso seja isso, quando algum processo seu não esteja funcionando bem, não se esqueça de tirar print e salvar novas imagens de acordo com sua tela e salvar na pasta com o mesmo nome e sempre em `.png`, a pasta das imagens é `/static/img/game`. Tudo isso está descrito no repositório como requisitos para o bot poder funcionar corretamente, não se esqueça de ler tudo antes.
