### ISSUE TITLE
OSError: screen grab failed

### ISSUE THREAD

**Issue by dicroh** [guimatheus92/Bot_SpaceCrypto#2]
INFO | Function: go_to_ships | 02/17/2022 12:22:13: Bot (SPG):  Going to ships menu..
```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at C:\Users\dicroh\Downloads\Bot_SpaceCrypto-main\Bot_SpaceCrypto-main\main.py:21> exception=OSError('screen grab failed')>
Traceback (most recent call last):
  File "C:\Users\dicroh\Downloads\Bot_SpaceCrypto-main\Bot_SpaceCrypto-main\main.py", line 115, in main
    await asyncio.create_task(first_start(app_name=app[1]))
  File "C:\Users\dicroh\Downloads\Bot_SpaceCrypto-main\Bot_SpaceCrypto-main\bot.py", line 178, in first_start
    await asyncio.create_task(send_ships_to_fight(app_name=app_name))
  File "C:\Users\dicroh\Downloads\Bot_SpaceCrypto-main\Bot_SpaceCrypto-main\bot.py", line 349, in send_ships_to_fight
    buttons = list(pyautogui.locateAllOnScreen(FightImgBtn, confidence=0.99))
  File "C:\Users\dicroh\AppData\Local\Programs\Python\Python39\lib\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\dicroh\AppData\Local\Programs\Python\Python39\lib\site-packages\pyautogui\__init__.py", line 201, in locateAllOnScreen
    return pyscreeze.locateAllOnScreen(*args, **kwargs)
  File "C:\Users\dicroh\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 397, in locateAllOnScreen
    screenshotIm = screenshot(region=None) # the locateAll() function must handle cropping to return accurate coordinates, so don't pass a region here.
  File "C:\Users\dicroh\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 145, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\dicroh\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 457, in _screenshot_win32
    im = ImageGrab.grab()
  File "C:\Users\dicroh\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\ImageGrab.py", line 43, in grab
    offset, size, data = Image.core.grabscreen_win32(
OSError: screen grab failed
```

**Comment by guimatheus92** [comment]
Pelo que eu vi da lista de pacotes que você tem no seu Python, está faltando algumas bibliotecas para você instalar. Você usa o Python na sua máquina? Caso não, execute os seguintes comandos:

```
pip freeze > requirements_old.txt
pip uninstall -r requirements_old.txt
```

Depois vá até a pasta do bot com o `cmd` e instala os pacotes necessários novamente:

`pip install -r requirements.txt`

Caso você precise dos pacotes que já está instalado, então somente execute o comando de `install` acima e executa o bot de novo pra ver se vai.
Quando você executa o comanda `pip freeze` você precisa ter exatamente as mesmas bibliotecas que eu recomendo.

**Comment by guimatheus92** [comment]
> Guilherme, boa tarde! Amigo, será que o bot consegue gerenciar mais de uma conta?rs

Opa! Sim, meu primo ta usando em duas contas com 60 naves em cada, está funcionando normal! Porém ele perder um pouco mais de tempo nesse jogo em especifico, porque tem muitas naves pra rodar na lista, então pode ser que ele não avance muito longe nas waves com VARIAS contas. Mas funciona sim!

**Comment by GustavordSantos1811** [comment]
> 

Outra duvida, e se eu colocar abrir 2 maquinas virtuais será que assim ficar melhor, pois hoje realmente o site tem delay para tudo rsrs
Qual você acha que rodaria melhor?

**Comment by guimatheus92** [comment]
> > 
> 
> Outra duvida, e se eu colocar abrir 2 maquinas virtuais será que assim ficar melhor, pois hoje realmente o site tem delay para tudo rsrs Qual você acha que rodaria melhor?

Olha esse seria um dos meus próximos testes, que é criar máquinas virtuais e deixar ele rodando uma em cada, mas não tive tempo de fazer nada disso ainda rs

Eu acredito sim que vai ser MUITO melhor, então se puder me dar um feedback depois como ficou esse seu teste por favor rs

**Comment by GustavordSantos1811** [comment]
Combinado, vou realizar os testes e te falo. Minha ideia é ter 3 maquinas com o macro rodando.
Até a noite te mando o feedback. Obrigado!!

**Comment by GustavordSantos1811** [comment]
![image](https://user-images.githubusercontent.com/99906469/154586896-6a387470-f633-4506-be17-45f17fc6c44d.png)


> > Realizando o procedimento no momento. Obrigado pelo feedback no troubleshooting
> 
> Deu certo?

O meu esta dando esse erro.
Estou tentando resolver 
INFO | Function: connect_wallet | 02/17/2022 20:09:15: Checking if needs to connect wallet..
INFO | Function: play_game | 02/17/2022 20:09:15: Checking if needs to play game..
INFO | Function: login_metamask | 02/17/2022 20:09:15: Checking if need to login in Metamask..

**Comment by guimatheus92** [comment]
> ![image](https://user-images.githubusercontent.com/99906469/154586896-6a387470-f633-4506-be17-45f17fc6c44d.png)
> 
> > > Realizando o procedimento no momento. Obrigado pelo feedback no troubleshooting
> > 
> > 
> > Deu certo?
> 
> O meu esta dando esse erro. Estou tentando resolver INFO | Function: connect_wallet | 02/17/2022 20:09:15: Checking if needs to connect wallet.. INFO | Function: play_game | 02/17/2022 20:09:15: Checking if needs to play game.. INFO | Function: login_metamask | 02/17/2022 20:09:15: Checking if need to login in Metamask..

Mas qual erro? Por enquanto o seu está certo, ele está rodando e estava vendo se tinha funções pra ativar.
Caso algum processo seu não esteja funcionando bem, não se esqueça de tirar print e salvar novas imagens de acordo com sua tela e salvar na pasta com o mesmo nome e sempre em `.png`.

**Comment by GustavordSantos1811** [comment]
> > ![image](https://user-images.githubusercontent.com/99906469/154586896-6a387470-f633-4506-be17-45f17fc6c44d.png)
> > > > Realizando o procedimento no momento. Obrigado pelo feedback no troubleshooting
> > > 
> > > 
> > > Deu certo?
> > 
> > 
> > O meu esta dando esse erro. Estou tentando resolver INFO | Function: connect_wallet | 02/17/2022 20:09:15: Checking if needs to connect wallet.. INFO | Function: play_game | 02/17/2022 20:09:15: Checking if needs to play game.. INFO | Function: login_metamask | 02/17/2022 20:09:15: Checking if need to login in Metamask..
> 
> Mas qual erro? Porque essa imagem que me mandou, não é mensagem de erro. Por enquanto o seu está certo, ele está rodando e estava vendo se tinha funções pra ativar. Caso algum processo seu não esteja funcionando bem, não se esqueça de tirar print e salvar novas imagens de acordo com sua tela e salvar na pasta com o mesmo nome e sempre em `.png`.

Guilherme, consegui fazer rodar.. porém fiquei com uma duvida...acabou a energia de todas minhas naves... ele não colocou as outras... o que tenho que fazer? pois eu tenho 60 naves.
Vlw

**Comment by GustavordSantos1811** [comment]
![image](https://user-images.githubusercontent.com/99906469/154606226-a0e9f4ff-51c2-4afd-9311-a06638ffb77b.png)
outra coisa... eu abri o macro nessa tela... tem varias naves full porém ele não procura...como posso ativar?

**Comment by AbilioDade** [comment]
Salve Galera, eu queria saber se ele troca automatico as naves quando chega no Boss 9, porque senão as naves acabam morrendo todas no Boss 10 e nao da tempo de trocar com o bot.

**Comment by flroexus** [comment]
how to fix?

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

**Comment by guimatheus92** [comment]
> Salve Galera, eu queria saber se ele troca automatico as naves quando chega no Boss 9, porque senão as naves acabam morrendo todas no Boss 10 e nao da tempo de trocar com o bot.

Troca sim! Já cheguei no 16 desse jeito se eu não me engano.
Quando acaba todas as naves na batalha, ele identifica a imagem `zero-ships.png` da pasta `/static/img/game`, então se as naves estiverem zeradas ele só adiciona novas naves, caso contrario ele remove alguma e adiciona novas (mas isso quase nunca acontece).

Caso algum processo seu não esteja funcionando bem, não se esqueça de tirar print e salvar novas imagens de acordo com sua tela e salvar na pasta com o mesmo nome e sempre em ` .png`.

**Comment by guimatheus92** [comment]
> how to fix?
> 
> ```
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [1 lines of output]
>       ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
>       [end of output]
> ```

Which version of `python` did you install? You can check running the following code: `python --version`

If your version is not `3.9.9`, make sure to take a look at the [README.md](https://github.com/guimatheus92/Bot_BombCrypto/blob/main/README.md) file, you will see that you will need to install [Python](https://github.com/guimatheus92/Bot_BombCrypto/wiki/How-to-execute-BombCrypto-bot) `3.9.9` version. So uninstall your python if it's not the right version and install the correct one. You can also follow the tutorial available on how to install Python.

**Comment by GustavordSantos1811** [comment]
> > > > ![image](https://user-images.githubusercontent.com/99906469/154586896-6a387470-f633-4506-be17-45f17fc6c44d.png)
> > > > > > Realizando o procedimento no momento. Obrigado pelo feedback no troubleshooting
> > > > > 
> > > > > 
> > > > > Deu certo?
> > > > 
> > > > 
> > > > O meu esta dando esse erro. Estou tentando resolver INFO | Function: connect_wallet | 02/17/2022 20:09:15: Checking if needs to connect wallet.. INFO | Function: play_game | 02/17/2022 20:09:15: Checking if needs to play game.. INFO | Function: login_metamask | 02/17/2022 20:09:15: Checking if need to login in Metamask..
> > > 
> > > 
> > > Mas qual erro? Porque essa imagem que me mandou, não é mensagem de erro. Por enquanto o seu está certo, ele está rodando e estava vendo se tinha funções pra ativar. Caso algum processo seu não esteja funcionando bem, não se esqueça de tirar print e salvar novas imagens de acordo com sua tela e salvar na pasta com o mesmo nome e sempre em `.png`.
> > 
> > 
> > Guilherme, consegui fazer rodar.. porém fiquei com uma duvida...acabou a energia de todas minhas naves... ele não colocou as outras... o que tenho que fazer? pois eu tenho 60 naves. Vlw
> 
> Opa que bom! Esse é o importante, fazer funcionar. Quando acaba todas as naves na batalha, ele identifica a imagem `zero-ships.png` da pasta `/static/img/game`, então se as naves estiverem zeradas ele só adiciona novas naves, caso contrario ele remove alguma e adiciona novas (mas isso quase nunca acontece).
> 
> Caso algum processo seu não esteja funcionando bem, não se esqueça de tirar print e salvar novas imagens de acordo com sua tela e salvar na pasta com o mesmo nome e sempre em `.png`.

Deu certo, última dúvida kkkk qnd ativo o multi contas.. ele me fala que tenho 0 contas.. onde que coloco qnts contas eu tenho?

**Comment by flroexus** [comment]
> > how to fix?
> > ```
> >   Preparing metadata (setup.py) ... error
> >   error: subprocess-exited-with-error
> > 
> >   × python setup.py egg_info did not run successfully.
> >   │ exit code: 1
> >   ╰─> [1 lines of output]
> >       ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
> >       [end of output]
> > ```
> 
> Which version of `python` did you install? You can check running the following code: `python --version`
> 
> If your version is not `3.9.9`, make sure to take a look at the [README.md](https://github.com/guimatheus92/Bot_BombCrypto/blob/main/README.md) file, you will see that you will need to install [Python](https://github.com/guimatheus92/Bot_BombCrypto/wiki/How-to-execute-BombCrypto-bot) `3.9.9` version. So uninstall your python if it's not the right version and install the correct one. You can also follow the tutorial available on how to install Python.

Yes, i have 3.9.9 and it is installed clean

**Comment by guimatheus92** [comment]
> > 
> 
> Montei maquinas virtuais com linux, com isso tive que parar de usar o seu script.

Sim, precisa ser em Windows, é só seguir os requisitos que eu deixei disponivel nesse repositório.
