### ISSUE TITLE
Opção de Pausar as operações

### ISSUE THREAD

**Issue by evertonurbanii** [guimatheus92/Bot_SpaceCrypto#21]
Algo q sinto falta em todos os bots de todos os jogos, seria uma opção de PAUSAR as operações, para q possa fazer algo na VM e apos isso voltar de onde parou. No seu bot daria certinho pra fazer pq ele opera as ABAS com identificação de nome, então é possivel ele voltar exatamente de onde parou.

**Comment by guimatheus92** [comment]
> Algo q sinto falta em todos os bots de todos os jogos, seria uma opção de PAUSAR as operações, para q possa fazer algo na VM e apos isso voltar de onde parou. No seu bot daria certinho pra fazer pq ele opera as ABAS com identificação de nome, então é possivel ele voltar exatamente de onde parou.

O jeito de "pausar" essa execução, é quando você clica na tela do `cmd` durante a execução, ele só irá voltar ao normal após você apertar a tecla "Enter" por exemplo. Mas isso não é uma funcionalidade a ser implantada, é algo nativo do Windows já.

**Comment by evertonurbanii** [comment]
Perfeito.. nao sabia.... só clicar na tela do cmd entao né.... show
