### ISSUE TITLE
Tela preta/Contas desativadas

### ISSUE THREAD

**Issue by evertonurbanii** [guimatheus92/Bot_SpaceCrypto#22]
![AnyDesk_zzrmsXFfyA](https://user-images.githubusercontent.com/40852711/154781429-df278627-5577-40d1-8b2e-9ec7487f9b3c.png)
Alguma ideia do q possa ser? Todas as ABAS ficaram com a tela preta, e o jogo cai.. veja no grafico abaixo do usa da CPU como cai geral o processamento.. acusando q as 4 contas estão desativadas.

**Comment by evertonurbanii** [comment]
![AnyDesk_YqG1lD414m](https://user-images.githubusercontent.com/40852711/154781539-b8b39bd6-32e6-4bf1-bb4a-0bdd7bbb1bdf.png)
Na tela do bot apareceu essa msg de erro.....

**Comment by guimatheus92** [comment]
> ![AnyDesk_zzrmsXFfyA](https://user-images.githubusercontent.com/40852711/154781429-df278627-5577-40d1-8b2e-9ec7487f9b3c.png) Alguma ideia do q possa ser? Todas as ABAS ficaram com a tela preta, e o jogo cai.. veja no grafico abaixo do usa da CPU como cai geral o processamento.. acusando q as 4 contas estão desativadas.

> ![AnyDesk_zzrmsXFfyA](https://user-images.githubusercontent.com/40852711/154781429-df278627-5577-40d1-8b2e-9ec7487f9b3c.png) Alguma ideia do q possa ser? Todas as ABAS ficaram com a tela preta, e o jogo cai.. veja no grafico abaixo do usa da CPU como cai geral o processamento.. acusando q as 4 contas estão desativadas.

Amigo, cuidado com o tanto de issues que você abre quando não é relacionado ao script ou funcionamento em si.
Esse tipo de problema que está me passando é relacionado ao jogo, VM, conexão, qualquer outra coisa.. pois o script está funcionando normalmente (inclusive você mesmo me avisou), tente ver se não é o browser, atualizar o browse limpando o cache (CTRL + SHIFT + R), etc.
Lembrando que quando o bot identifica o erro no jogo, ele já atualiza automaticamente pra você.
