### ISSUE TITLE
Como organizar as janelas para multiacount?

### ISSUE THREAD

**Issue by tiranossaur** [guimatheus92/Bot_SpaceCrypto#23]
Oi amigo primeiramente obrigado pelo programa!

Como devo organizar as janelas para rodar mais de 1 conta? (Ainda nao testei)

1- As contas tem que ficar tudo visiveis na tela? (em qualquer lugar da tela?)
2 - Ou Em modo cascata?

Agradeço

**Comment by evertonurbanii** [comment]
Boa tarde!
Basta deixar todas abertas, uma sobre a outra. 
Observando que tem a necessidade de inserir o nome de cada Perfil Criado no BRAVE dentro das configurações do BOT conforme descrito.

**Comment by tiranossaur** [comment]
Ele loga mas na tela das naves nao acha acao nenhuma pra fazer, vou começar tirar print dos botao denovo vamo ve

**Comment by guimatheus92** [comment]
> Ele loga mas na tela das naves nao acha acao nenhuma pra fazer, vou começar tirar print dos botao denovo vamo ve

É justamente o que o @evertonurbanii falou, só deixar as janelas em 100%, assim como o zoom do Brave.
Todas devem ter um nome de perfil, e serem organizadas no arquivo `config.yaml`.

Caso algum processo seu não esteja funcionando bem, não se esqueça de tirar print e salvar novas imagens de acordo com sua tela e salvar na pasta com o mesmo nome e sempre em `.png`, a pasta das imagens é `/static/img/game`. Tudo isso está descrito no repositório como requisitos para o bot poder funcionar corretamente, não se esqueça de ler tudo antes.
