### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by chberta** [guimatheus92/Bot_SpaceCrypto#24]
Bom Dia. 
Tentei varias vezes mas fica dando este erro ao  exeutar o comando. 

**pip install -r requirements.txt**

tenho o **Python 3.10.2**
Erro neste pacote pip install pandas==1.1.5

instalei o Visual Studio e agora este erro

      pandas/_libs/src/klib\khash.h(563): warning C4090: 'fun‡Æo': qualificadores 'const' diferentes
      pandas/_libs/src/parser/io.c(139): error C2065: 'ssize_t': identificador nÆo declarado
      pandas/_libs/src/parser/io.c(139): error C2146: erro de sintaxe: ';' ausente antes do identificador 'rv'
      pandas/_libs/src/parser/io.c(139): error C2065: 'rv': identificador nÆo declarado
      pandas/_libs/src/parser/io.c(145): error C2065: 'rv': identificador nÆo declarado
      pandas/_libs/src/parser/io.c(145): warning C4267: 'fun‡Æo': conversÆo de 'size_t' para 'unsigned int', poss¡vel perda de dados
      pandas/_libs/src/parser/io.c(146): error C2065: 'rv': identificador nÆo declarado
      pandas/_libs/src/parser/io.c(157): error C2065: 'rv': identificador nÆo declarado
      pandas/_libs/src/parser/io.c(158): error C2065: 'rv': identificador nÆo declarado
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
--------------------------------------------------------------------
--------------------------------------------------------------------
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by evertonurbanii** [comment]
Boa tarde!
Não funciona com a versão Python 3.10.2 conforme descrito, é necessário instalar a versão Python 3.9.9.

**Comment by chberta** [comment]
sou leigo como faço tenho q desistalar versão 3.10.2 e coloca a 3.9.9 ?

**Comment by evertonurbanii** [comment]
Isso mesmo

**Comment by guimatheus92** [comment]
Conforme o @evertonurbanii o erro era porque não estava usando a versão correta do Python, a versão certa é a `Python 3.9.9`.
