### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by alaindaniel** [guimatheus92/Bot_SpaceCrypto#25]
```
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by guimatheus92** [comment]
> ```
> Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [1 lines of output]
>       ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> ```

Qual a versão do Python você instalou? Pode conferir através do comando `python --version` no `cmd`. 
O certo é a versão `3.9.9` que eu recomendei. Desinstala e instala de novo, na duvida segue o tutorial que eu deixei pronto aqui já [How to execute SpaceCrypto bot](https://github.com/guimatheus92/Bot_SpaceCrypto/wiki/How-to-execute-SpaceCrypto-bot). Não esquece de ler tudo certinho e não pular nenhuma etapa das minhas recomendações, porque cada computador tem sua peculiaridade, aí evita erro.

**Comment by alaindaniel** [comment]
Obrigado pela ajuda amigo. Resolvi. Instalei o python 3.9.9 e as dependências uma a uma e funcionou. Obrigado
