### ISSUE TITLE
Ao executar main.py

### ISSUE THREAD

**Issue by alaindaniel** [guimatheus92/Bot_SpaceCrypto#26]
```
C:\Bot_SpaceCrypto-main>main.py
Traceback (most recent call last):
  File "C:\Bot_SpaceCrypto-main\main.py", line 4, in <module>
    from bot import reload_page, start_game, login_metamask, new_map, SetTrigger, skip_error_on_game, how_many_coins, first_start, send_ships_to_fight, refresh_game, continue_fighting
  File "C:\Bot_SpaceCrypto-main\bot.py", line 8, in <module>
    from controllers import setup_logger, take_screenshot, read_configurations, send_telegram_pic
  File "C:\Bot_SpaceCrypto-main\controllers.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by guimatheus92** [comment]
> ```
> C:\Bot_SpaceCrypto-main>main.py
> Traceback (most recent call last):
>   File "C:\Bot_SpaceCrypto-main\main.py", line 4, in <module>
>     from bot import reload_page, start_game, login_metamask, new_map, SetTrigger, skip_error_on_game, how_many_coins, first_start, send_ships_to_fight, refresh_game, continue_fighting
>   File "C:\Bot_SpaceCrypto-main\bot.py", line 8, in <module>
>     from controllers import setup_logger, take_screenshot, read_configurations, send_telegram_pic
>   File "C:\Bot_SpaceCrypto-main\controllers.py", line 2, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
> ```

Reparei que abriu dois issues aqui no Git, cuidado com o spam de erros.

Qual a versão do Python você instalou? Pode conferir através do comando `python --version` no `cmd`. 
O certo é a versão `3.9.9` que eu recomendei. Desinstala e instala de novo, na duvida segue o tutorial que eu deixei pronto aqui já [How to execute SpaceCrypto bot](https://github.com/guimatheus92/Bot_SpaceCrypto/wiki/How-to-execute-SpaceCrypto-bot). Não esquece de ler tudo certinho e não pular nenhuma etapa das minhas recomendações, porque cada computador tem sua peculiaridade, aí evita erro. a

**Comment by alaindaniel** [comment]
Perdão amigo. É porque foram dois erros diferentes. Mas já havia resolvido. Muito obrigado pela ajuda
