### ISSUE TITLE
Remove nave da batalha 

### ISSUE THREAD

**Issue by rogeriojim** [guimatheus92/Bot_SpaceCrypto#3]
O bot esta removendo as naves da batalha sem precisar.

**Comment by guimatheus92** [comment]
O bot sempre inicia removendo as naves da lista, adiciona as naves de acordo com sua configuração (`full` ou `all`). Durante a wave, quando acaba todas as naves, ele identifica a imagem `zero-ships.png` da pasta `/static/img/game`, então se as naves estiverem zeradas ele só adiciona novas naves, caso contrario ele remove alguma e adiciona novas (mas isso quase nunca acontece).

Caso algum processo seu não esteja funcionando bem, não se esqueça de tirar print e salvar novas imagens de acordo com sua tela e salvar na pasta com o mesmo nome e sempre em `.png`.
