### ISSUE TITLE
ERROR exeption

### ISSUE THREAD

**Issue by tiranossaur** [guimatheus92/Bot_SpaceCrypto#30]
Ta dando esse erro ai tava no fight derrepente deu isso...
![image](https://user-images.githubusercontent.com/14037089/154817951-54bb3144-3e82-42ee-a859-d80818667d1a.png)

**Comment by guimatheus92** [comment]
> Ta dando esse erro ai tava no fight derrepente deu isso... ![image](https://user-images.githubusercontent.com/14037089/154817951-54bb3144-3e82-42ee-a859-d80818667d1a.png)

Cara eu peguei esse erro uma vez também mas ainda não consegui identificar o porque, vou deixar essa issue aberta pra ver se alguém consegue ajudar ok? Neste caso, infelizmente temos que fechar o bot manualmente e abrir novamente.

**Comment by tiranossaur** [comment]
> > Ta dando esse erro ai tava no fight derrepente deu isso... ![image](https://user-images.githubusercontent.com/14037089/154817951-54bb3144-3e82-42ee-a859-d80818667d1a.png)
> 
> Cara eu peguei esse erro uma vez também mas ainda não consegui identificar o porque, vou deixar essa issue aberta pra ver se alguém consegue ajudar ok? Neste caso, infelizmente temos que fechar o bot manualmente e abrir novamente.

Pois é man, o foda que acontece meio direto, entao fica inviavel o uso :(, seria maravilhoso se funcionasse blz, mas com esse erro ai n da pra usar. Arruma esse trem ai pra nos man se nao vou ter q amargar 190 pila num bot pago q eu nao tenho acesso ao codigo e o medo afff...

**Comment by guimatheus92** [comment]
> > > Ta dando esse erro ai tava no fight derrepente deu isso... ![image](https://user-images.githubusercontent.com/14037089/154817951-54bb3144-3e82-42ee-a859-d80818667d1a.png)
> > 
> > 
> > Cara eu peguei esse erro uma vez também mas ainda não consegui identificar o porque, vou deixar essa issue aberta pra ver se alguém consegue ajudar ok? Neste caso, infelizmente temos que fechar o bot manualmente e abrir novamente.
> 
> Pois é man, o foda que acontece meio direto, entao fica inviavel o uso :(, seria maravilhoso se funcionasse blz, mas com esse erro ai n da pra usar. Arruma esse trem ai pra nos man se nao vou ter q amargar 190 pila num bot pago q eu nao tenho acesso ao codigo e o medo afff...

Mas aqui acontece bem raramente aqui viu? Hoje reparei por exemplo que deu erro (obviamente) quando acabou a bateria do meu pc, então ele não teve acesso a imagem que ele precisava no momento. Pode ter algo a ver talvez..

**Comment by tiranossaur** [comment]
> > > > Ta dando esse erro ai tava no fight derrepente deu isso... ![image](https://user-images.githubusercontent.com/14037089/154817951-54bb3144-3e82-42ee-a859-d80818667d1a.png)
> > > 
> > > 
> > > Cara eu peguei esse erro uma vez também mas ainda não consegui identificar o porque, vou deixar essa issue aberta pra ver se alguém consegue ajudar ok? Neste caso, infelizmente temos que fechar o bot manualmente e abrir novamente.
> > 
> > 
> > Pois é man, o foda que acontece meio direto, entao fica inviavel o uso :(, seria maravilhoso se funcionasse blz, mas com esse erro ai n da pra usar. Arruma esse trem ai pra nos man se nao vou ter q amargar 190 pila num bot pago q eu nao tenho acesso ao codigo e o medo afff...
> 
> Mas aqui acontece bem raramente aqui viu? Hoje reparei por exemplo que deu erro (obviamente) quando acabou a bateria do meu pc, então ele não teve acesso a imagem que ele precisava no momento. Pode ter algo a ver talvez..

Entao o not aki fica na bateria direto, e eu to rodando aquele outro bot q tem aki no git tbm, só que nao tem mult conta funciona legal, mas esse seu da esses erro de print direto. Add eu ai no discord bora papear tiranossaur#9906
