### ISSUE TITLE
With update pagination has been added

### ISSUE THREAD

**Issue by ugurgokdere** [guimatheus92/Bot_SpaceCrypto#31]
Hi, 
Thanks for your efforts.
With the new release pagination needs to be addressed on the bot.

**Comment by ugurgokdere** [comment]
Closed after your update #32

**Comment by guimatheus92** [comment]
Hi! Thank you.
For now, I won't be updating this feature because there is no need.
What I'm doing is sorting the ships list with "Max Ammo", so ships gets sorted automatically and with that there is no use for pagination, and we even gets a little bit of time in the picking ships.
