### ISSUE TITLE
Mudança na hora de escolher as naves

### ISSUE THREAD

**Issue by GustavordSantos1811** [guimatheus92/Bot_SpaceCrypto#32]
Fala Gui
Boa tarde!
Como você está?
Amigo eles colocaram uma aba nova para mudar a pagina de naves.
![image](https://user-images.githubusercontent.com/99906469/154992604-13fb3602-8d29-44a0-afa0-54decbe79a96.png)
Você consegue atualizar para esse novo formato?
E agora ficou mto mais rápido ao selecionar as naves também rsrs

Vlw

**Comment by guimatheus92** [comment]
> Fala Gui Boa tarde! Como você está? Amigo eles colocaram uma aba nova para mudar a pagina de naves. ![image](https://user-images.githubusercontent.com/99906469/154992604-13fb3602-8d29-44a0-afa0-54decbe79a96.png) Você consegue atualizar para esse novo formato? E agora ficou mto mais rápido ao selecionar as naves também rsrs
> 
> Vlw

Opa, salve!
Tudo ótimo e por ai?

Cara pelo que eu analisei, não há necessidade de atualizar a paginação por enquanto (até porque to gastando muito tempo nisso sem ter muito retorno rs).
O que eu estou fazendo: Organizando a lista das naves por "Max Ammo", e ele escolhe as naves com mais munições pra lutar, dessa forma, ele não precisa ir nas listas procurando por naves e ganha MUITO mais tempo com isso entendeu?
Recomendo fazer o mesmo por enquanto!

Mas eu to torcendo para eles adicionarem um botão "All" pra facilitar a nossa vida e deixar o bot infinitamente mais rapido.
Eles deixaram menos pesado o game mesmo, finalmente! hahahaha
