### ISSUE TITLE
cmd nao consegue instalar o requiriments do jeito certo 

### ISSUE THREAD

**Issue by Yuri021** [guimatheus92/Bot_SpaceCrypto#33]
[
![image](https://user-images.githubusercontent.com/35474136/155052876-e650791d-c07d-4796-b0d2-7e000ba5bc96.png)
](url)

**Comment by guimatheus92** [comment]
> [ ![image](https://user-images.githubusercontent.com/35474136/155052876-e650791d-c07d-4796-b0d2-7e000ba5bc96.png) ](url)

Qual a versão do Python você instalou? Pode conferir através do comando `python --version` no `cmd`. 
O certo é a versão `3.9.9` que eu recomendei. Caso tenha uma versão diferente, desinstala e instala de novo, na duvida segue o tutorial que eu deixei pronto aqui já [How to execute SpaceCrypto bot](https://github.com/guimatheus92/Bot_SpaceCrypto/wiki/How-to-execute-SpaceCrypto-bot). Não esquece de ler tudo certinho e não pular nenhuma etapa das minhas recomendações, porque cada computador tem sua peculiaridade, aí evita erro.
