### ISSUE TITLE
Help não roda no linux Erro "No matching distribution found for pywin32==303"

### ISSUE THREAD

**Issue by PINGOMAX** [guimatheus92/Bot_SpaceCrypto#6]
Caro amigo estou tentando rodar no Linux porem, ao tentar instalar o requirements esta dando este erro "No matching distribution found for pywin32==303"
Ja fiz alguns procedimento mas não obtive sucesso.
![2022-02-18_05-44](https://user-images.githubusercontent.com/68357776/154650374-b723720f-04a7-402b-bb0d-ca0f91445b20.png)
![2022-02-18_05-50](https://user-images.githubusercontent.com/68357776/154650403-592f76e0-3d8e-4aa0-9135-b36dc3c29a2f.png)

**Comment by guimatheus92** [comment]
> Caro amigo estou tentando rodar no Linux porem, ao tentar instalar o requirements esta dando este erro "No matching distribution found for pywin32==303" Ja fiz alguns procedimento mas não obtive sucesso. ![2022-02-18_05-44](https://user-images.githubusercontent.com/68357776/154650374-b723720f-04a7-402b-bb0d-ca0f91445b20.png) ![2022-02-18_05-50](https://user-images.githubusercontent.com/68357776/154650403-592f76e0-3d8e-4aa0-9135-b36dc3c29a2f.png)

Opa! Eu estou utilizando pacotes que utilizam interfaces do Windows pro multiaccount funcionar corretamente, então infelizmente só funciona em Windows, por isso eu deixei citado nos [requirements](https://github.com/guimatheus92/Bot_SpaceCrypto#requirements) qual as versões suportadas.

O pacote `pywinauto` utiliza automações através do Microsoft Windows GUI.
O que você pode tentar fazer, é remover este pacote dos `requirements.txt` e tentar usar o bot pra ver se vai com o parâmetro `enable_multiaccount` igual a `False` no arquivo `config.yaml`. Mas não tenho certeza se vai funcionar.
