### ISSUE TITLE
Selecionar até BOSS XX (SURRENDER)

### ISSUE THREAD

**Issue by evertonurbanii** [guimatheus92/Bot_SpaceCrypto#9]
É possivel selecionar até qual BOSS ele vai aplicar o SURRENDER?
Isso seria bem interessante pra ajudar algumas contas mais fracas e outras fortes com estrategia de FARM.

**Comment by chberta** [comment]
Eu gostei desta idea de selecionar ate qual BOSS ir pois tenho 40 naves vou ate BOSS 18 com sorte inicio o 19.
como tenho menos de 50% de chace de passar o BOSS 18 se marcar por exemplo BOSS 17 pra retornar vou ter GANHO melhor... pois se entro no 18 e reseto consigo ir tranquilo ate os BOSS 5
